host: 127.0.0.1
port: 27017
database: glass
username: root
password: pass
connection-timeout: 30000
idle-timeout: 600000
max-lifetime: 1800000
minimum-idle: 10
maximum-pool-size: 10
notification-channel-id: 0